sudo: false

language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 2.6
      arch: ppc64le
    - python: 2.7
      arch: ppc64le
    - python: 3.4
      arch: ppc64le
    - python: 3.5
      arch: ppc64le
    - python: 3.6
      arch: ppc64le
    - python: 3.7
      arch: ppc64le
      dist: xenial
      sudo: true

  fast_finish: true

install:
  - pip install codecov

script:
 - python unitTests.py
 - python simple_unit_tests.py

after_success:
  - codecov
